apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3tirewebapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: 3tirewebapp
  template:
    metadata:
      labels:
        app: 3tirewebapp
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
