apiVersion: apps/v1
kind: Deployment

metadata:
  name: threetirewebapp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: threetirewebapp

  template:
    metadata:
      labels:
        app: threetirewebapp

    spec:
      containers:
        - name: threetirewebapp
          image: nginx
          ports:
            - containerPort: 80