apiVersion: v1
kind: Service
metadata:
  name: 3tirewebapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: 3tirewebapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
