apiVersion: v1
kind: Service
metadata:
  name:  threetirewebapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: threetirewebapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
