apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: dev-team-role
  namespace: default

rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch

  - apiGroups: [""]
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch