apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: 3tirewebapp-dev
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-dev-puz5t00f.vault.azure.net/
      authType: ManagedIdentity
