apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: 3tirewebapp-dev
  annotations:
    azure.workload.identity/client-id: "95a2e733-cf07-4030-9656-c10a508799c0"

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: 3tirewebapp-dev
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-dev-3wk61obz.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets-sa

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials-from-kv
  namespace: 3tirewebapp-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: postgres-credentials-from-kv
    creationPolicy: Merge
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres-username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres-database