resources:
  - namespace.yaml
  - postgres-complete.yaml
  - backend-complete.yaml
  - frontend-complete.yaml
  - external-secrets-placeholder.yaml
  - network-policies.yaml
  - scaling-resilience.yaml
  - kyverno-policies.yaml
  - ingress.yaml
  - external-secret.yaml

images:
  - name: cheikhfall/frontend
    newTag: v1.0.1

  - name: cheikhfall/aks-devsecops-app
    newTag: latest

  - name: postgres
    newTag: "15"