resources:
  - namespace.yaml
  - postgres-complete.yaml
  - backend-complete.yaml
  - frontend-complete.yaml
  - external-secrets-placeholder.yaml
  - network-policies.yaml
  - scaling-resilience.yaml

images:
  - name: piyushasachdeva/frontend
    newName: cheikhfall/frontend
    newTag: v1.0.0
  - name: piyushasachdeva/backend
    newName: cheikhfall/aks-devsecops-app
    newTag: latest
  - name: postgres
    newTag: "15"