apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: aks-platform-admins

subjects:
  - kind: Group

    # Microsoft Entra ID Group Object ID
    name: "38815ae9-f42f-4a21-85d7-d45dc1004c4b"

    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io