apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-root
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: require-run-as-non-root
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Containers must not run as root"
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true
