apiVersion: v1
kind: Namespace
metadata:
  name: 3tirewebapp-dev
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted2