apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  namespace: 3tirewebapp-dev
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: secure-pod
    image: nginxinc/nginx-unprivileged:stable
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL